Added image size to media on css to account for screen size
NdikumNdifor/wdd330-team06-repo pull request #20
Opened 2024-05-10 05:21 UTC by sarihahope

Added some css to respond to different screen sizes. 

![111](https://github.com/NdikumNdifor/wdd330-team06-repo/assets/130946364/a2e25ce8-54b1-448e-8669-9054e681331a)
![444](https://github.com/NdikumNdifor/wdd330-team06-repo/assets/130946364/43785e16-69bc-4e8a-8db8-a3d4ab76e82f)
![222](https://github.com/NdikumNdifor/wdd330-team06-repo/assets/130946364/027ce242-bf48-4828-adeb-1c8963a986d2)

2024-05-11 21:52 UTC, isaachuffman37 approved these changes

2024-05-11 21:55 UTC, isaachuffman37 requested changes

2024-05-11 21:55 UTC, isaachuffman37 commented on src/css/style.css
> +
Is there any way you can adjust the size of the logo in the top left when the screen size is mobile?

2024-05-12 00:35 UTC, hccazado approved these changes
Looks better with these display updates

2024-05-12 00:46 UTC, BrandonMHerrin approved these changes

2024-05-12 04:39 UTC, isaachuffman37 approved these changes

2024-05-12 04:39 UTC, merged